```{r}
library(ggplot2)
library(forcats)


data <- read.csv("../data/countries_by_cities.csv")
data <- data[data$country %in% c("SAD", "Kanada", "Velika Britanija", "Indija", "Australija", "Meksiko", "JAR", "Novi Zeland", "Irska", "Njemačka"),]

data$duration <- as.numeric(data$duration..seconds.)

data$duration_minutes <- data$duration / 60 / 60

# Calculate average duration by country in minutes
avg_duration_by_country <- aggregate(data$duration_minutes, by=list(data$country), FUN=mean, na.rm=TRUE)

# Sort the data by average duration
avg_duration_by_country

avg_duration_by_country <- avg_duration_by_country[order(avg_duration_by_country$x), ]
avg_duration_by_country

# Plotting
ggplot(avg_duration_by_country, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Prosječno trajanje događaja za TOP 10 država",
       x = "Država",
       y = "Prosječno trajanje događaja (sati)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y

ggsave("../figures/TOP10drzava_trajanje_po_drzavi1.png")

```

```{r}
data <- read.csv("../data/countries_by_cities.csv")
data <- data[data$country %in% c("SAD", "Kanada", "Velika Britanija", "Indija", "Australija", "Meksiko", "JAR", "Novi Zeland", "Irska", "Njemačka"),]

data$duration <- as.numeric(data$duration..seconds.)
data_filtered <- data %>%
  filter(duration <= 60*60*24)

data_filtered$duration_minutes <- data_filtered$duration / 60 

# Calculate average duration by country in minutes
# Calculate average duration by country in minutes
avg_duration_by_country <- aggregate(data_filtered$duration_minutes, by=list(data_filtered$country), FUN=mean, na.rm=TRUE)

# Sort the data by average duration
avg_duration_by_country <- avg_duration_by_country[order(avg_duration_by_country$x),]

# Plotting
ggplot(avg_duration_by_country, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Prosječno trajanje događaja za TOP 10 država(max 24h)",
       x = "Država",
       y = "Prosječno trajanje događaja (minute)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y

ggsave("../figures/TOP10drzava_trajanje_po_drzavi2.png")
```
```{r}
data <- read.csv("../data/countries_by_cities.csv")

data$duration <- as.numeric(data$duration..seconds.)

data$duration_minutes <- data$duration / 60

# Calculate average duration by country in minutes
avg_duration_by_country <- aggregate(data$duration_minutes, by=list(data$country), FUN=mean, na.rm=TRUE)

# Sort the data by average duration
avg_duration_by_country

avg_duration_by_country <-  avg_duration_by_country[avg_duration_by_country$Group.1 != "",]

avg_duration_by_country <- avg_duration_by_country[order(avg_duration_by_country$x), ]
avg_duration_by_country


top_10_max_duration_countries <- tail(avg_duration_by_country, 10)
top_10_max_duration_countries

top_10_max_duration_countries$x <- top_10_max_duration_countries$x / 60 # sad bude u satima


top_10_min_duration_countries <- head(avg_duration_by_country, 10)
top_10_max_duration_countries$x <- top_10_max_duration_countries$x * 60 # sad bude u sekundama

# Plotting
ggplot(top_10_max_duration_countries, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "10 država s najvećim prosječnim vremenom događaja",
       x = "Država",
       y = "Prosječno trajanje događaja (sati)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y

ggsave("../figures/10_država_s_najvecim_prosječnim_vremenom.png")



ggplot(top_10_min_duration_countries, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "10 država s najmanjim prosječnim vremenom događaja",
       x = "Država",
       y = "Prosječno trajanje događaja (sekunde)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y
ggsave("../figures/10_država_s_najmanjim_prosječnim_vremenom.png")


```
Sad filtrirano da su max dogadanja do 1 dana


```{r}
data <- read.csv("../data/countries_by_cities.csv")

data$duration <- as.numeric(data$duration..seconds.)

data
data_filtered <- data %>%
  filter(duration <= 60*60*24)

data_filtered[data_filtered$country == "Egipat",]

data_filtered$duration_minutes <- data_filtered$duration / 60

# Calculate average duration by country in minutes
avg_duration_by_country <- aggregate(data_filtered$duration_minutes, by=list(data_filtered$country), FUN=mean, na.rm=TRUE)

# Sort the data by average duration
avg_duration_by_country

avg_duration_by_country <-  avg_duration_by_country[avg_duration_by_country$Group.1 != "",]

avg_duration_by_country <- avg_duration_by_country[order(avg_duration_by_country$x), ]
avg_duration_by_country


top_10_max_duration_countries <- tail(avg_duration_by_country, 10)
top_10_max_duration_countries

top_10_max_duration_countries$x <- top_10_max_duration_countries$x


top_10_min_duration_countries <- head(avg_duration_by_country, 10)
top_10_min_duration_countries$x <- top_10_min_duration_countries$x * 60 # sad bude u sekundama

# Plotting
ggplot(top_10_max_duration_countries, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "10 država s najvećim prosječnim vremenom događaja",
       x = "Država",
       y = "Prosječno trajanje događaja (minute)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y

ggsave("../figures/10_država_s_najvecim_prosječnim_vremenom_FILTRIRANO.png")


ggplot(top_10_min_duration_countries, aes(x = reorder(Group.1, x), y = x)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "10 država s najmanjim prosječnim vremenom događaja",
       x = "Država",
       y = "Prosječno trajanje događaja (sekunde)") +
  theme_minimal() +
  coord_flip()  # Rotiranje osi x i y

ggsave("../figures/10_država_s_najmanjim_prosječnim_vremenom_FILTRIRANO.png")

```

