---
title: "najcesce_rijeci"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("tidytext")
library("tm")
library(wordcloud2)
library(wordcloud)
library(RColorBrewer)

```

Ucitavanje podataka i čišćenje od znakova:

```{r}
data <- read.csv("../data/complete.csv")
head(data)

data$comments <- gsub("&#\\d+|&quot;|&amp;", " ", data$comments)
data$comments <- gsub("[[:digit:]]+", " ", data$comments)
data$comments <- gsub("[\\(\\)]", " ", data$comments)



symbols <- c(",", ".", "/")
data$comments <- sapply(data$comments, function(comment) {
  # Remove additional symbols
  for (symbol in symbols) {
    comment <- gsub(symbol, " ", comment, fixed = TRUE)
  }
  
  return(comment)
})

head(data, 20)
```

Izvlacenje rijeci i njihove frekvencije, micanje stopwords

```{r}

comments <-  data$comments



rijeci <- data.frame(table(unlist(strsplit(tolower(comments), " "))))


# Rename columns for clarity
colnames(rijeci) <- c("Word", "Freq")

# Remove English stopwords
stopwords <- stopwords("en")
rijeci <- rijeci %>%
  filter(!Word %in% c(stopwords, ""))


# Arrange by frequency in descending order
rijeci <- rijeci %>%
  arrange(desc(Freq))
#rijeci
```

```{r}
#sada cemo dodati wordcloud


wordcloud(rijeci$Word, rijeci$Freq, min.freq = 1, max.words = 100, random.order = FALSE, rot.per = 0.35, colors = brewer.pal(8, "Dark2"))
```

```{r}
#koristit UFO.png kao masku
#figPath <- "UFO.png"
wordcloud2(rijeci, size = 1.5, color='random-dark')
#a <- wordcloud2(rijeci, figPath = figPath, size = 1.5, color='random-dark')

```