```{r}
library(dplyr)

us_state_names <- c("al" = "Alabama", "ak" = "Alaska", "az" = "Arizona", "ar" = "Arkansas", "ca" = "California",
                 "co" = "Colorado", "ct" = "Connecticut", "de" = "Delaware", "fl" = "Florida", "ga" = "Georgia",
                 "hi" = "Hawaii", "id" = "Idaho", "il" = "Illinois", "in" = "Indiana", "ia" = "Iowa",
                 "ks" = "Kansas", "ky" = "Kentucky", "la" = "Louisiana", "me" = "Maine", "md" = "Maryland",
                 "ma" = "Massachusetts", "mi" = "Michigan", "mn" = "Minnesota", "ms" = "Mississippi", "mo" = "Missouri",
                 "mt" = "Montana", "ne" = "Nebraska", "nv" = "Nevada", "nh" = "New Hampshire", "nj" = "New Jersey",
                 "nm" = "New Mexico", "ny" = "New York", "nc" = "North Carolina", "nd" = "North Dakota", "oh" = "Ohio",
                 "ok" = "Oklahoma", "or" = "Oregon", "pa" = "Pennsylvania", "ri" = "Rhode Island", "sc" = "South Carolina",
                 "sd" = "South Dakota", "tn" = "Tennessee", "tx" = "Texas", "ut" = "Utah", "vt" = "Vermont",
                 "va" = "Virginia", "wa" = "Washington", "wv" = "West Virginia", "wi" = "Wisconsin", "wy" = "Wyoming")

# Kreiranje rječnika za kanadske provincije i teritorije
canada_province_names <- c("on" = "Ontario", "bc" = "British Columbia", "ab" = "Alberta", "qc" = "Quebec", "mb" = "Manitoba",
                 "ns" = "Nova Scotia", "nb" = "New Brunswick", "sk" = "Saskatchewan",
                 "pq" = "Quebec", "pr" = "Prince Edward Island", "nf" = "Newfoundland",
                 "nt" = "Northwest Territories", "pe" = "Prince Edward Island", "yt" = "Yukon", "yk" = "Yukon")

# Kreiranje rječnika za druge lokacije koje nisu ni SAD ni Kanada
other_location_names <- c("dc" = "District of Columbia", "sa" = "South Australia", "vi" = "Virgin Islands")


data <- read.csv("../data/complete.csv")





```




```{r}

# Funkcija koja će prepoznati državu ili teritorij
get_country <- function(state) {
  if (tolower(state) %in% names(us_state_names)) {
    return("us")
  } else if (tolower(state) %in% names(canada_province_names)) {
    return("ca")
  } else {
    return(state)
  }
}

# Filtriranje podataka
data <- data %>%
  filter(state != "Nepoznato" & state != "") %>%
  mutate(full_state = case_when(
    tolower(state) %in% names(us_state_names) ~ us_state_names[tolower(state)],
    tolower(state) %in% names(canada_province_names) ~ canada_province_names[tolower(state)],
    tolower(state) %in% names(other_location_names) ~ other_location_names[tolower(state)],
    TRUE ~ state
  )) %>%
  mutate(country = sapply(state, get_country))


data

data <- data[data$country == 'us',]
data

```






```{r}

# Filtriranje podataka
state_counts_filtered <- data %>%
  filter(state != "Nepoznato" & state != "") %>%
  count(state) %>%
  arrange(desc(n))  # Poredaj od najvećeg do najmanjeg broja zapisa

state_counts_filtered


state_counts_filtered <- state_counts_filtered  %>%
  mutate(state = case_when(
    tolower(state) %in% names(us_state_names) ~ us_state_names[tolower(state)],
    TRUE ~ state
  ))


state_counts_filtered
```
```{r}

ggplot(state_counts_filtered, aes(x = reorder(state, n), y = n)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Broj nečega po državama",
       x = "Država",
       y = "Broj nečega") +
  scale_x_discrete(expand = expansion(add = -10)) +  # Dodajemo dodatan razmak između oznaka na x-osi
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```




